In [ ]:
# ***Prachi - 8025320072***
# ***Assignment 2***

In [1]:
#1. Create a Data File (20000 × 10000) Using Random Module

import numpy as np

# Define size
rows = 20000
cols = 10000

# Generate random matrix (float32 to reduce memory usage)
data = np.random.rand(rows, cols).astype(np.float32)

# Save to file
np.save("large_matrix.npy", data)

print("Data file created successfully!")
print("Shape:", data.shape)


Data file created successfully!
Shape: (20000, 10000)


In [2]:
# 2. Assign Subsequent Rows to First Row Elements

import numpy as np

# Example matrix
matrix = np.random.randint(1, 10, (5, 5))
print("Original Matrix:\n", matrix)

# Assign first row to all rows
matrix[:] = matrix[0]

print("\nModified Matrix:\n", matrix)


Original Matrix:
 [[3 4 9 1 6]
 [6 1 1 9 8]
 [4 3 9 9 9]
 [7 9 2 5 6]
 [6 4 3 8 4]]

Modified Matrix:
 [[3 4 9 1 6]
 [3 4 9 1 6]
 [3 4 9 1 6]
 [3 4 9 1 6]
 [3 4 9 1 6]]


In [3]:
# 3. Group Similar Elements into Matrix

import numpy as np

matrix = np.random.randint(1, 20, (5, 5))
print("Original Matrix:\n", matrix)

# Group even and odd elements
even = matrix[matrix % 2 == 0]
odd = matrix[matrix % 2 != 0]

print("\nEven Elements:", even)
print("Odd Elements:", odd)


Original Matrix:
 [[ 6  4  6  1  8]
 [14 19 17 16 19]
 [18  7  9 11  1]
 [ 4 12  5 11  6]
 [18  5  4 19  8]]

Even Elements: [ 6  4  6  8 14 16 18  4 12  6 18  4  8]
Odd Elements: [ 1 19 17 19  7  9 11  1  5 11  5 19]


In [4]:
# 4. Add and Subtract Matrices

import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Addition
add = A + B
print("\nAddition:\n", add)

# Subtraction
sub = A - B
print("\nSubtraction:\n", sub)


Matrix A:
 [[7 6 7]
 [6 4 9]
 [6 2 3]]

Matrix B:
 [[1 3 9]
 [5 3 5]
 [9 7 1]]

Addition:
 [[ 8  9 16]
 [11  7 14]
 [15  9  4]]

Subtraction:
 [[ 6  3 -2]
 [ 1  1  4]
 [-3 -5  2]]


In [5]:
# 5. Create n × n Matrix Where Sum of Opposite Corners of Every Sub-matrix is Even

import numpy as np

n = 4

# Create matrix with all even numbers
matrix = np.random.randint(1, 50, (n, n)) * 2

print("Matrix:\n", matrix)


Matrix:
 [[44 68 54 74]
 [48 98 68 32]
 [38 98 92 90]
 [84 54 92 72]]


In [7]:
# 6. Row-wise Element Addition in Tuple Matrix

# Tuple matrix
matrix = ((5, 2, 4),
          (4, 5, 1),
          (3, 6, 5))

print("Original Tuple Matrix:", matrix)

# Row-wise sum
row_sums = tuple(sum(row) for row in matrix)

print("Row-wise Addition:", row_sums)


Original Tuple Matrix: ((5, 2, 4), (4, 5, 1), (3, 6, 5))
Row-wise Addition: (11, 10, 14)
